name: 'tests'
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v2
      with:
        name: binaries
    - run: tar -xf binaries.tar
    - run: ./uhdm-integration/.github/ci.sh
      shell: bash
