# Filenames starting with / to avoid false matches by suffix

VERILATOR_ONLY_SOURCE_FILENAMES=\
/kmac_pkg.sv \
/otbn_model_pkg.sv \
/tl_main_pkg.sv \
/tl_peri_pkg.sv \
/top_earlgrey_rnd_cnst_pkg.sv \
/adc_ctrl_core.sv \
/adc_ctrl_intr.sv \
/adc_ctrl_reg_top.sv \
/aes_core.sv \
/aes_ctrl_reg_shadowed.sv \
/aes_key_expand.sv \
/aes_reg_top.sv \
/aes_sbox_dom.sv \
/aes_sub_bytes.sv \
/aes.sv \
/alert_handler_reg_top.sv \
/alert_handler_reg_wrap.sv \
/alert_handler.sv \
/aon_osc.sv \
/aon_timer_reg_top.sv \
/aon_timer.sv \
/ast_dft.sv \
/ast_reg_top.sv \
/ast.sv \
/clkmgr_byp.sv \
/clkmgr_reg_top.sv \
/clkmgr.sv \
/csrng_core.sv \
/csrng_reg_top.sv \
/csrng.sv \
/dmi_cdc.sv \
/edn_core.sv \
/edn_reg_top.sv \
/edn.sv \
/entropy_src_core.sv \
/entropy_src_reg_top.sv \
/entropy_src.sv \
/entropy_src_watermark_reg.sv \
/flash_ctrl_core_reg_top.sv \
/flash_ctrl_lcmgr.sv \
/flash_ctrl.sv \
/flash_mp_data_region_sel.sv \
/flash_mp.sv \
/flash_phy_rd.sv \
/flash_phy.sv \
/gpio_reg_top.sv \
/gpio.sv \
/hmac_reg_top.sv \
/hmac.sv \
/i2c_core.sv \
/i2c_reg_top.sv \
/i2c.sv \
/io_clk.sv \
/io_osc.sv \
/keccak_2share.sv \
/keccak_round.sv \
/keymgr_ctrl.sv \
/keymgr_kmac_if.sv \
/keymgr_reg_top.sv \
/keymgr_sideload_key_ctrl.sv \
/keymgr.sv \
/kmac_app.sv \
/kmac_core.sv \
/kmac_entropy.sv \
/kmac_errchk.sv \
/kmac_msgfifo.sv \
/kmac_reg_top.sv \
/kmac_staterd.sv \
/kmac.sv \
/lc_ctrl_fsm.sv \
/lc_ctrl_kmac_if.sv \
/lc_ctrl_reg_top.sv \
/lc_ctrl.sv \
/otbn_core_model.sv \
/otbn_reg_top.sv \
/otbn_rf_base.sv \
/otbn_rf_bignum.sv \
/otbn_rf_snooper_if.sv \
/otbn_rnd.sv \
/otbn_stack_snooper_if.sv \
/otbn.sv \
/otp_ctrl_core_reg_top.sv \
/otp_ctrl_part_buf.sv \
/otp_ctrl_scrmbl.sv \
/otp_ctrl.sv \
/pattgen_core.sv \
/pattgen_reg_top.sv \
/pattgen.sv \
/pinmux_jtag_buf.sv \
/pinmux_reg_top.sv \
/pinmux_strap_sampling.sv \
/pinmux.sv \
/pinmux_wkup.sv \
/prim_alert_receiver.sv \
/prim_alert_sender.sv \
/prim_arbiter_ppc.sv \
/prim_clock_buf.sv \
/prim_clock_div.sv \
/prim_clock_gating.sv \
/prim_clock_gating_sync.sv \
/prim_clock_inv.sv \
/prim_clock_meas.sv \
/prim_clock_mux2.sv \
/prim_dom_and_2share.sv \
/prim_edge_detector.sv \
/prim_edn_req.sv \
/prim_esc_receiver.sv \
/prim_esc_sender.sv \
/prim_fifo_async_sram_adapter.sv \
/prim_fifo_async.sv \
/prim_flash.sv \
/prim_generic_flash_bank.sv \
/prim_generic_flash.sv \
/prim_generic_ram_1p.sv \
/prim_generic_rom.sv \
/prim_lc_sync.sv \
/prim_packer.sv \
/prim_present.sv \
/prim_ram_1p_scr.sv \
/prim_ram_1p.sv \
/prim_ram_2p_async_adv.sv \
/prim_reg_cdc.sv \
/prim_rom_adv.sv \
/prim_rom.sv \
/prim_slicer.sv \
/prim_sram_arbiter.sv \
/prim_subreg_arb.sv \
/prim_subreg_cdc.sv \
/prim_subreg_ext_async.sv \
/prim_subreg_shadow.sv \
/prim_subst_perm.sv \
/prim_sync_reqack_data.sv \
/pwm_reg_top.sv \
/pwm.sv \
/pwrmgr_reg_top.sv \
/pwrmgr.sv \
/rom_ctrl_counter.sv \
/rom_ctrl_fsm.sv \
/rom_ctrl_mux.sv \
/rom_ctrl_regs_reg_top.sv \
/rom_ctrl_scrambled_rom.sv \
/rom_ctrl.sv \
/rstmgr_ctrl.sv \
/rstmgr_por.sv \
/rstmgr_reg_top.sv \
/rstmgr.sv \
/rv_core_addr_trans.sv \
/rv_core_ibex_cfg_reg_top.sv \
/rv_core_ibex.sv \
/rv_dm_regs_reg_top.sv \
/rv_dm_rom_reg_top.sv \
/rv_dm.sv \
/rv_plic_reg_top.sv \
/rv_plic.sv \
/rv_plic_target.sv \
/rv_timer_reg_top.sv \
/rv_timer.sv \
/sensor_ctrl_reg_top.sv \
/sensor_ctrl.sv \
/sha3pad.sv \
/sha3.sv \
/spi_device_reg_top.sv \
/spi_device.sv \
/spid_upload.sv \
/spi_fwmode.sv \
/spi_host_command_cdc.sv \
/spi_host_data_cdc.sv \
/spi_host_reg_top.sv \
/spi_host.sv \
/spi_readcmd.sv \
/spi_s2p.sv \
/spi_tpm.sv \
/sram_ctrl_regs_reg_top.sv \
/sram_ctrl.sv \
/sys_clk.sv \
/sys_osc.sv \
/sysrst_ctrl_reg_top.sv \
/sysrst_ctrl.sv \
/tlul_adapter_sram.sv \
/tlul_assert_multiple.sv \
/tlul_fifo_async.sv \
/tlul_fifo_sync.sv \
/tlul_socket_1n.sv \
/tlul_socket_m1.sv \
/tlul_sram_byte.sv \
/top_earlgrey.sv \
/uart_core.sv \
/uartdpi.sv \
/uart_reg_top.sv \
/uart.sv \
/usb_clk.sv \
/usbdev_aon_wake.sv \
/usbdev_iomux.sv \
/usbdev_linkstate.sv \
/usbdev_reg_top.sv \
/usbdev.sv \
/usb_osc.sv \
/xbar_main.sv \
/xbar_peri.sv \

VERILATOR_AND_SURELOG_SOURCE_FILENAMES=\
/vio_pgd.sv \
/vcmain_pgd.sv \
/vcc_pgd.sv \
/vcaon_pgd.sv \
/usb_fs_tx.sv \
/usb_fs_tx_mux.sv \
/usb_fs_rx.sv \
/usb_fs_nb_pe.sv \
/usb_fs_nb_out_pe.sv \
/usb_fs_nb_in_pe.sv \
/usbdpi.sv \
/usbdev_usbif.sv \
/usbdev_flop_2syncpulse.sv \
/uart_tx.sv \
/uart_rx.sv \
/tlul_sink.sv \
/tlul_rsp_intg_gen.sv \
/tlul_rsp_intg_chk.sv \
/tlul_err.sv \
/tlul_err_resp.sv \
/tlul_data_integ_enc.sv \
/tlul_data_integ_dec.sv \
/tlul_cmd_intg_gen.sv \
/tlul_cmd_intg_chk.sv \
/tlul_assert.sv \
/tlul_adapter_reg.sv \
/tlul_adapter_host.sv \
/timer_core.sv \
/sysrst_ctrl_ulp.sv \
/sysrst_ctrl_ulpfsm.sv \
/sysrst_ctrl_timerfsm.sv \
/sysrst_ctrl_pin.sv \
/sysrst_ctrl_keyintr.sv \
/sysrst_ctrl_keyfsm.sv \
/sysrst_ctrl_combo.sv \
/sysrst_ctrl_combofsm.sv \
/sysrst_ctrl_comboact.sv \
/sysrst_ctrl_autoblock.sv \
/sw_test_status_if.sv \
/sram2tlul.sv \
/spi_passthrough.sv \
/spi_p2s.sv \
/spi_host_window.sv \
/spi_host_shift_register.sv \
/spi_host_fsm.sv \
/spi_host_core.sv \
/spi_host_byte_select.sv \
/spi_host_byte_merge.sv \
/spi_fwm_txf_ctrl.sv \
/spid_status.sv \
/spid_readsram.sv \
/sim_sram_if.sv \
/rom_ctrl_compare.sv \
/rng.sv \
/pwrmgr_slow_fsm.sv \
/pwrmgr_fsm.sv \
/pwrmgr_cdc.sv \
/prim_sync_slow_fast.sv \
/prim_sync_reqack.sv \
/prim_subreg.sv \
/prim_secded_hamming_22_16_enc.sv \
/prim_secded_39_32_enc.sv \
/prim_secded_39_32_dec.sv \
/prim_ram_1p_adv.sv \
/prim_pulse_sync.sv \
/prim_generic_flop_2sync.sv \
/prim_fifo_sync.sv \
/prim_count.sv \
/prim_arbiter_tree.sv \
/prim_arbiter_fixed.sv \
/otp_ctrl_part_unbuf.sv \
/otp_ctrl_lfsr_timer.sv \
/otp_ctrl_lci.sv \
/otp_ctrl_kdi.sv \
/otp_ctrl_dai.sv \
/otbn_stack.sv \
/lc_ctrl_signal_decode.sv \
/entropy_src_main_sm.sv \
/entropy_src_ack_sm.sv \
/edn_main_sm.sv \
/edn_ack_sm.sv \
/alert_handler_esc_timer.sv \
/alert_handler_accu.sv \
/aes_sel_buf_chk.sv \
/aes_reg_status.sv \
/aes_prng_masking.sv \
/prim_prince.sv \
/prim_packer_fifo.sv \
/prim_lfsr.sv \
/prim_generic_flop.sv \
/prim_generic_buf.sv \
/prim_flop.sv \
/prim_flop_2sync.sv \
/prim_buf.sv \
/otp_ctrl_ecc_reg.sv \
/aes_cipher_control.sv \
/aes_cipher_core.sv \
/aes_control.sv \
/alert_handler_ping_timer.sv \
/csrng_cmd_stage.sv \
/csrng_ctr_drbg_cmd.sv \
/csrng_ctr_drbg_gen.sv \
/csrng_ctr_drbg_upd.sv \
/csrng_main_sm.sv \
/csrng_track_sm.sv \
/dev_entropy.sv \
/dm_csrs.sv \
