name: 'tests'
runs:
  using: "composite"
  steps:
    - name: Download binaries
      uses: actions/download-artifact@v2
      with:
        name: binaries

    # See https://github.com/actions/upload-artifact/issues/38
    - name: Extract
      run: tar -xf binaries.tar

    - name: Build & Test
      run: ./uhdm-integration/.github/ci.sh
